version: '3.1'

services:

  gigo_dev_ui_nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dev.crt:/etc/nginx/dev.crt
      - ./dev.key:/etc/nginx/dev.key
    network_mode: "host"

  mitm_server:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the Dockerfile is in the same directory as docker-compose.yml
    network_mode: "host"
